version: "3.8"

services:
  comfyui:
    image: hzmdocker/runpod-worker-comfy:dev
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
    env_file:
      - .env
    runtime: nvidia
    volumes:
      - ./data/comfyui/output:/comfyui/output
